### ISSUE TITLE
Bookmarks: Show folders

### ISSUE THREAD

**Issue by maxwfreu** [maxwfreu/ScrumptiousTab#2]
## Description
Our custom bookmark bar currently does not show folders. Let's add functionality to be able to show folders, pages within folders, and folders within folders.

## Tasks
- [ ] Render folders in bookmarks bar
- [ ] Clicking folders should render dropdown with list of pages
- [ ] Subfolders should reuse same folder component
